[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"

[ja]
  languageName = "Japanese"
  contentDir = "content/ja"
  weight = 15
  [de.params]
    languageISO = "JP"